-- Create Feature Store
CREATE OR REPLACE FEATURE STORE CUSTOMER_FS;

-- Add Engineered Feature Table to Store
ALTER FEATURE STORE CUSTOMER_FS ADD FEATURE TABLE FEATURE_DB.PUBLIC.CUSTOMER_FEATURES
PRIMARY KEY (CUSTOMER_ID);

-- Describe Feature Store
SHOW FEATURE STORES;
