-- Create Database & Schema (if not exists)
CREATE DATABASE IF NOT EXISTS RAW_DB;
CREATE SCHEMA IF NOT EXISTS RAW_DB.PUBLIC;

-- Create Raw Source Table
CREATE OR REPLACE TABLE RAW_DB.PUBLIC.SALES_DATA (
    CUSTOMER_ID INT,
    ORDER_ID INT,
    ORDER_AMOUNT FLOAT,
    ORDER_DATE TIMESTAMP,
    REGION STRING
);
