CREATE DATABASE IF NOT EXISTS FEATURE_DB;
CREATE SCHEMA IF NOT EXISTS FEATURE_DB.PUBLIC;

-- Feature Engineering Table
CREATE OR REPLACE TABLE FEATURE_DB.PUBLIC.CUSTOMER_FEATURES AS
SELECT
    CUSTOMER_ID,
    COUNT(ORDER_ID) AS TOTAL_ORDERS,
    AVG(ORDER_AMOUNT) AS AVG_ORDER_AMOUNT,
    SUM(ORDER_AMOUNT) AS TOTAL_SPENT,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF('day', MIN(ORDER_DATE), MAX(ORDER_DATE)) AS CUSTOMER_TENURE_DAYS,
    COUNT(DISTINCT REGION) AS REGION_DIVERSITY,
    MAX(ORDER_AMOUNT) AS MAX_ORDER_VALUE,
    MIN(ORDER_AMOUNT) AS MIN_ORDER_VALUE,
    
    -- Example categorical encoding
    CASE 
        WHEN COUNT(*) > 2 THEN 'HIGH VALUE'
        ELSE 'LOW VALUE'
    END AS CUSTOMER_SEGMENT

FROM RAW_DB.PUBLIC.SALES_DATA
GROUP BY CUSTOMER_ID;
